export ZDOTDIR=${ZDOTDIR:-$HOME/.config/zsh}

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-$HOME/.xdg}
export XDG_PROJECTS_DIR=${XDG_PROJECTS_DIR:-$HOME/Projects}

export SSH_CONFIG_HOME=${SSH_CONFIG_HOME:-$XDG_CONFIG_HOME/ssh}
export SSH_DATA_HOME=${SSH_DATA_HOME:-$XDG_DATA_HOME/ssh}

export LANG=en_GB.UTF-8
export LC_ALL="en_GB.UTF-8"